services:
  elasticsearch:
    image: elasticsearch:7.17.25
    container_name: elasticsearch
    environment:
      - node.name=es-single-node
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false  # Tắt bảo mật (chỉ cho môi trường phát triển)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-network
#  kibana:
#    container_name: kibana
#    image: kibana:7.17.25
#    restart: always
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
#    ports:
#      - '5601:5601'
#    depends_on:
#      - elasticsearch
#    networks:
#      - es-network

volumes:
  esdata:
    driver: local

networks:
  es-network:
    driver: bridge
