--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_user_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_user_entity (
    id character varying(255) NOT NULL,
    role character varying(255),
    email character varying(255),
    password character varying(255),
    username character varying(255),
    CONSTRAINT admin_user_entity_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'EMPLOYEE'::character varying, 'EMPLOYER'::character varying])::text[])))
);


ALTER TABLE public.admin_user_entity OWNER TO postgres;

--
-- Name: ban_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ban_notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text,
    status character varying(255),
    reason character varying(255),
    title text,
    user_id character varying(255),
    CONSTRAINT ban_notification_status_check CHECK (((status)::text = ANY ((ARRAY['SENT'::character varying, 'DELIVERED'::character varying, 'READ'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.ban_notification OWNER TO postgres;

--
-- Name: ban_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ban_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ban_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    id character varying(255) NOT NULL,
    content text,
    conversation_id bigint,
    recipient_id character varying(255),
    sender_id character varying(255),
    "timestamp" timestamp(6) without time zone,
    type character varying(255),
    caption text
);


ALTER TABLE public.chat_message OWNER TO postgres;

--
-- Name: company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company (
    id character varying(255) NOT NULL,
    role character varying(255),
    address character varying(255),
    created_at date,
    description text,
    email character varying(255),
    field character varying(255),
    logo character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    state character varying(255),
    wallpaper character varying(255),
    website character varying(255),
    company_subscription_id character varying(255),
    CONSTRAINT company_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'EMPLOYEE'::character varying, 'EMPLOYER'::character varying])::text[]))),
    CONSTRAINT company_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIVE'::character varying, 'RESTRICT'::character varying, 'BAN'::character varying])::text[])))
);


ALTER TABLE public.company OWNER TO postgres;

--
-- Name: company_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company_plan (
    id character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255),
    period character varying(255),
    price bigint,
    price_id character varying(255),
    product_id character varying(255),
    priority integer,
    limit_post integer
);


ALTER TABLE public.company_plan OWNER TO postgres;

--
-- Name: company_plan_company_subscriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company_plan_company_subscriptions (
    company_plan_id character varying(255) NOT NULL,
    company_subscriptions_id character varying(255) NOT NULL
);


ALTER TABLE public.company_plan_company_subscriptions OWNER TO postgres;

--
-- Name: company_subscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company_subscription (
    id character varying(255) NOT NULL,
    email character varying(255),
    end_date date,
    start_date date,
    status character varying(255),
    company_id character varying(255),
    plan_id character varying(255)
);


ALTER TABLE public.company_subscription OWNER TO postgres;

--
-- Name: conversation_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversation_users (
    conversation_id bigint NOT NULL,
    users character varying(255)
);


ALTER TABLE public.conversation_users OWNER TO postgres;

--
-- Name: conversations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversations (
    id bigint NOT NULL,
    last_message character varying(255),
    created_at timestamp(6) without time zone,
    type character varying(10),
    receiver_id character varying(255),
    sender_id character varying(255)
);


ALTER TABLE public.conversations OWNER TO postgres;

--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job (
    job_id bigint NOT NULL,
    benefits text,
    created_at date,
    description text,
    experience integer NOT NULL,
    expire_date date,
    field character varying(255),
    gender character varying(255),
    location character varying(255),
    max_salary integer NOT NULL,
    min_salary integer NOT NULL,
    province character varying(255),
    quantity integer NOT NULL,
    requirements text,
    role character varying(255),
    state character varying(255),
    title text,
    type character varying(255),
    update_at date,
    work_time character varying(255),
    company_id character varying(255),
    CONSTRAINT job_state_check CHECK (((state)::text = ANY ((ARRAY['BANNED'::character varying, 'PENDING'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.job OWNER TO postgres;

--
-- Name: job_application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_application (
    id bigint NOT NULL,
    created_date date,
    cv_url text NOT NULL,
    reference_letter text,
    state character varying(255),
    job_job_id bigint,
    user_id character varying(255),
    CONSTRAINT job_application_state_check CHECK (((state)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.job_application OWNER TO postgres;

--
-- Name: job_application_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_applications (
    job_entity_job_id bigint NOT NULL,
    applications_id bigint NOT NULL
);


ALTER TABLE public.job_applications OWNER TO postgres;

--
-- Name: job_job_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job ALTER COLUMN job_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_tag (
    id character varying(255) NOT NULL,
    tag character varying(255)
);


ALTER TABLE public.job_tag OWNER TO postgres;

--
-- Name: report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.report (
    id bigint NOT NULL,
    company_id character varying(255),
    reason text NOT NULL,
    status character varying(255),
    user_id character varying(255) NOT NULL,
    job_id bigint,
    CONSTRAINT report_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'DONE'::character varying])::text[])))
);


ALTER TABLE public.report OWNER TO postgres;

--
-- Name: report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_entity (
    id character varying(255) NOT NULL,
    role character varying(255),
    address character varying(255),
    avatar character varying(255),
    created_at date,
    date_of_birth date,
    education_level character varying(255),
    email character varying(255),
    gender character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255),
    university character varying(255),
    CONSTRAINT user_entity_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'EMPLOYEE'::character varying, 'EMPLOYER'::character varying])::text[])))
);


ALTER TABLE public.user_entity OWNER TO postgres;

--
-- Name: user_entity_applied_jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_entity_applied_jobs (
    user_entity_id character varying(255) NOT NULL,
    applied_jobs_job_id bigint NOT NULL
);


ALTER TABLE public.user_entity_applied_jobs OWNER TO postgres;

--
-- Name: user_entity_cv; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_entity_cv (
    user_entity_id character varying(255) NOT NULL,
    cv text
);


ALTER TABLE public.user_entity_cv OWNER TO postgres;

--
-- Name: user_entity_saved_jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_entity_saved_jobs (
    user_entity_id character varying(255) NOT NULL,
    saved_jobs_job_id bigint NOT NULL
);


ALTER TABLE public.user_entity_saved_jobs OWNER TO postgres;

--
-- Name: user_entity_search_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_entity_search_history (
    user_entity_id character varying(255) NOT NULL,
    search_history text
);


ALTER TABLE public.user_entity_search_history OWNER TO postgres;

--
-- Data for Name: admin_user_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin_user_entity (id, role, email, password, username) FROM stdin;
125d5711-511c-4ea1-8b1b-0fcb8ac99858	ADMIN	kienluu61@gmail.com	12345678	admin
\.


--
-- Data for Name: ban_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ban_notification (id, created_at, message, status, reason, title, user_id) FROM stdin;
\.


--
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_message (id, content, conversation_id, recipient_id, sender_id, "timestamp", type, caption) FROM stdin;
\.


--
-- Data for Name: company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company (id, role, address, created_at, description, email, field, logo, name, password, phone, state, wallpaper, website, company_subscription_id) FROM stdin;
\.


--
-- Data for Name: company_plan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company_plan (id, description, name, period, price, price_id, product_id, priority, limit_post) FROM stdin;
price_1QSgTaFMfEC9tDRADZGlzGlM	\N	Pro	month	500000	price_1QSgTaFMfEC9tDRADZGlzGlM	prod_RLNEo0klDpuWTM	15	\N
price_1QSw8SFMfEC9tDRA6lC6x28Q	\N	Basic	month	300000	price_1QSw8SFMfEC9tDRA6lC6x28Q	prod_RLdPii9sz0QMtX	10	30
price_1QXe4uFMfEC9tDRAzFpTtdN9	Ultimate	Ultimate	year	4000000	price_1QXe4uFMfEC9tDRAzFpTtdN9	prod_RQV5VTL6sh2mQ6	20	\N
\.


--
-- Data for Name: company_plan_company_subscriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company_plan_company_subscriptions (company_plan_id, company_subscriptions_id) FROM stdin;
\.


--
-- Data for Name: company_subscription; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company_subscription (id, email, end_date, start_date, status, company_id, plan_id) FROM stdin;
\.


--
-- Data for Name: conversation_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.conversation_users (conversation_id, users) FROM stdin;
\.


--
-- Data for Name: conversations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.conversations (id, last_message, created_at, type, receiver_id, sender_id) FROM stdin;
\.


--
-- Data for Name: job; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job (job_id, benefits, created_at, description, experience, expire_date, field, gender, location, max_salary, min_salary, province, quantity, requirements, role, state, title, type, update_at, work_time, company_id) FROM stdin;
\.


--
-- Data for Name: job_application; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_application (id, created_date, cv_url, reference_letter, state, job_job_id, user_id) FROM stdin;
\.


--
-- Data for Name: job_applications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_applications (job_entity_job_id, applications_id) FROM stdin;
\.


--
-- Data for Name: job_tag; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_tag (id, tag) FROM stdin;
\.


--
-- Data for Name: report; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.report (id, company_id, reason, status, user_id, job_id) FROM stdin;
\.


--
-- Data for Name: user_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_entity (id, role, address, avatar, created_at, date_of_birth, education_level, email, gender, name, password, phone, university) FROM stdin;
\.


--
-- Data for Name: user_entity_applied_jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_entity_applied_jobs (user_entity_id, applied_jobs_job_id) FROM stdin;
\.


--
-- Data for Name: user_entity_cv; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_entity_cv (user_entity_id, cv) FROM stdin;
\.


--
-- Data for Name: user_entity_saved_jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_entity_saved_jobs (user_entity_id, saved_jobs_job_id) FROM stdin;
\.


--
-- Data for Name: user_entity_search_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_entity_search_history (user_entity_id, search_history) FROM stdin;
\.


--
-- Name: ban_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ban_notification_id_seq', 22, true);


--
-- Name: conversations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.conversations_id_seq', 10, true);


--
-- Name: job_application_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_application_id_seq', 21, true);


--
-- Name: job_job_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_job_id_seq', 64, true);


--
-- Name: report_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.report_id_seq', 31, true);


--
-- Name: admin_user_entity admin_user_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_user_entity
    ADD CONSTRAINT admin_user_entity_pkey PRIMARY KEY (id);


--
-- Name: ban_notification ban_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ban_notification
    ADD CONSTRAINT ban_notification_pkey PRIMARY KEY (id);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: company_plan company_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_plan
    ADD CONSTRAINT company_plan_pkey PRIMARY KEY (id);


--
-- Name: company_subscription company_subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_subscription
    ADD CONSTRAINT company_subscription_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: job_application job_application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT job_application_pkey PRIMARY KEY (id);


--
-- Name: job job_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_pkey PRIMARY KEY (job_id);


--
-- Name: job_tag job_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_tag
    ADD CONSTRAINT job_tag_pkey PRIMARY KEY (id);


--
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT report_pkey PRIMARY KEY (id);


--
-- Name: company_plan_company_subscriptions uk4t53u2ky1ig4yew8u297b6i8c; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_plan_company_subscriptions
    ADD CONSTRAINT uk4t53u2ky1ig4yew8u297b6i8c UNIQUE (company_subscriptions_id);


--
-- Name: company ukb0jfrguytg1yhif2xbjvu3ef4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT ukb0jfrguytg1yhif2xbjvu3ef4 UNIQUE (company_subscription_id);


--
-- Name: company_subscription ukmtk4wx2iqed2ibydvrldbvkaw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_subscription
    ADD CONSTRAINT ukmtk4wx2iqed2ibydvrldbvkaw UNIQUE (company_id);


--
-- Name: job_applications ukogybv14ns4ef1j6s3cnxyglmy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_applications
    ADD CONSTRAINT ukogybv14ns4ef1j6s3cnxyglmy UNIQUE (applications_id);


--
-- Name: user_entity_applied_jobs user_entity_applied_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_applied_jobs
    ADD CONSTRAINT user_entity_applied_jobs_pkey PRIMARY KEY (user_entity_id, applied_jobs_job_id);


--
-- Name: user_entity user_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity
    ADD CONSTRAINT user_entity_pkey PRIMARY KEY (id);


--
-- Name: user_entity_saved_jobs user_entity_saved_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_saved_jobs
    ADD CONSTRAINT user_entity_saved_jobs_pkey PRIMARY KEY (user_entity_id, saved_jobs_job_id);


--
-- Name: job_applications fk5hvl3qxr968x0h7lcujme9ou5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_applications
    ADD CONSTRAINT fk5hvl3qxr968x0h7lcujme9ou5 FOREIGN KEY (applications_id) REFERENCES public.job_application(id);


--
-- Name: company_plan_company_subscriptions fk5naicgv6fpnq4847fbjknra47; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_plan_company_subscriptions
    ADD CONSTRAINT fk5naicgv6fpnq4847fbjknra47 FOREIGN KEY (company_subscriptions_id) REFERENCES public.company_subscription(id);


--
-- Name: job fk5q04favsasq8y70bsei7wv8fc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT fk5q04favsasq8y70bsei7wv8fc FOREIGN KEY (company_id) REFERENCES public.company(id);


--
-- Name: conversation_users fk63p0tbk14kd41sn7v1cw6xp2f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversation_users
    ADD CONSTRAINT fk63p0tbk14kd41sn7v1cw6xp2f FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);


--
-- Name: job_applications fk76hmc3xa6582k0rhbgtjn1op3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_applications
    ADD CONSTRAINT fk76hmc3xa6582k0rhbgtjn1op3 FOREIGN KEY (job_entity_job_id) REFERENCES public.job(job_id);


--
-- Name: company_plan_company_subscriptions fk7j9pc8uc925ptifqwwh7hgwwh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_plan_company_subscriptions
    ADD CONSTRAINT fk7j9pc8uc925ptifqwwh7hgwwh FOREIGN KEY (company_plan_id) REFERENCES public.company_plan(id);


--
-- Name: company_subscription fkb6ftcva71bffj1ao5h2x8a4j9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_subscription
    ADD CONSTRAINT fkb6ftcva71bffj1ao5h2x8a4j9 FOREIGN KEY (company_id) REFERENCES public.company(id);


--
-- Name: company fkbq8ni77mtyxscg2p7xgsteoob; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT fkbq8ni77mtyxscg2p7xgsteoob FOREIGN KEY (company_subscription_id) REFERENCES public.company_subscription(id);


--
-- Name: job_application fkdgyjbtylx4g03tigw2j9odiap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fkdgyjbtylx4g03tigw2j9odiap FOREIGN KEY (user_id) REFERENCES public.user_entity(id);


--
-- Name: user_entity_saved_jobs fkfu5xgc0uc2n5y3o2u2eca0jsi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_saved_jobs
    ADD CONSTRAINT fkfu5xgc0uc2n5y3o2u2eca0jsi FOREIGN KEY (user_entity_id) REFERENCES public.user_entity(id);


--
-- Name: report fkg5pev9qjkdahxi4bxikpvmn7o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT fkg5pev9qjkdahxi4bxikpvmn7o FOREIGN KEY (job_id) REFERENCES public.job(job_id);


--
-- Name: user_entity_saved_jobs fkg6bo7vwgt7nhjfs284eb8n5hg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_saved_jobs
    ADD CONSTRAINT fkg6bo7vwgt7nhjfs284eb8n5hg FOREIGN KEY (saved_jobs_job_id) REFERENCES public.job(job_id);


--
-- Name: job_application fkgmp4pioxajpc7n0i9gnusbbou; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fkgmp4pioxajpc7n0i9gnusbbou FOREIGN KEY (job_job_id) REFERENCES public.job(job_id);


--
-- Name: company_subscription fkj47w487b9ukyyd1xtxuosluir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company_subscription
    ADD CONSTRAINT fkj47w487b9ukyyd1xtxuosluir FOREIGN KEY (plan_id) REFERENCES public.company_plan(id);


--
-- Name: user_entity_applied_jobs fkme523e966i3hifsbhb34yddtv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_applied_jobs
    ADD CONSTRAINT fkme523e966i3hifsbhb34yddtv FOREIGN KEY (user_entity_id) REFERENCES public.user_entity(id);


--
-- Name: conversations fknu4kjix8mk42rmuwnoqs3u7fl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fknu4kjix8mk42rmuwnoqs3u7fl FOREIGN KEY (sender_id) REFERENCES public.company(id);


--
-- Name: user_entity_search_history fkr0788hspherm9g075v0c02wg8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_search_history
    ADD CONSTRAINT fkr0788hspherm9g075v0c02wg8 FOREIGN KEY (user_entity_id) REFERENCES public.user_entity(id);


--
-- Name: user_entity_applied_jobs fkr16h9tb7ixhyh13rkdo4ekiyx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_applied_jobs
    ADD CONSTRAINT fkr16h9tb7ixhyh13rkdo4ekiyx FOREIGN KEY (applied_jobs_job_id) REFERENCES public.job(job_id);


--
-- Name: user_entity_cv fks52i3siienkn2p14emuwcnn31; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_entity_cv
    ADD CONSTRAINT fks52i3siienkn2p14emuwcnn31 FOREIGN KEY (user_entity_id) REFERENCES public.user_entity(id);


--
-- Name: conversations fksuxmraxa622d1n5qops132axm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fksuxmraxa622d1n5qops132axm FOREIGN KEY (receiver_id) REFERENCES public.user_entity(id);


--
-- PostgreSQL database dump complete
--

