#DATASOURCE
USER_NAME: postgres
PASSWORD: Luudinhkien_2003
URL: jdbc:postgresql://localhost:5432/jobfinder
DRIVER: org.postgresql.Driver
DIALECT: org.hibernate.dialect.PostgreSQLDialect
FRONT_END_URL: http://localhost:5173


CLOUDINARY_API_SECRET: UDQB-T_Rd9rqYc_XlRufz_qOu_c
CLOUDINARY_API_KEY: 583814582724325
CLOUDINARY_CLOUD_NAME: dmi3xizxq

#TOKEN
ACCESS_TOKEN_EXPIRE_TIME: 3600
REFRESH_TOKEN_EXPIRE_TIME: 31536000

