#DATASOURCE
USER_NAME: postgres
PASSWORD: Luudinhkien_2003
URL: jdbc:postgresql://localhost:5432/groupweb2
DRIVER: org.postgresql.Driver
DIALECT: org.hibernate.dialect.PostgreSQLDialect
#4003 is the frontend port, not the nginx port(80 by default)
# you may have frontend config like this in vite.config.ts
#server:{
#    port: 4003,
#    strictPort: true,
#    host: true,
#    origin: "http://0.0.0.0:4003",
#  }
# so the port that make requests to backend is 4003, not 80 of nginx, since 80 is just the port
#that request to get website's interface. all backend requests are made through 4003.
FRONT_END_URL: http://localhost:4003, http://frontend:4003, http://my-group-web.s3-website-ap-southeast-1.amazonaws.com
SECRET_PATH: /home/ec2-user/security.txt
CLOUDINARY_API_SECRET: UDQB-T_Rd9rqYc_XlRufz_qOu_c
CLOUDINARY_API_KEY: 583814582724325
CLOUDINARY_CLOUD_NAME: dmi3xizxq

#TOKEN
ACCESS_TOKEN_EXPIRE_TIME: 3600
REFRESH_TOKEN_EXPIRE_TIME: 31536000

#REDIS
REDIS_PASSWORD: Luudinhkien_2003
REDIS_PORT: 6390
REDIS_HOST: localhost
REDIS_DATABASE: 0