services:
  postgres:
    image: postgres:16
    container_name: jobfinder-database
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
#      - ../mobile_data.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jobfinder
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "jobfinder" ]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - .env

  elasticsearch:
    image: elasticsearch:7.17.25
    container_name: elasticsearch
    environment:
      - node.name=es-single-node
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - jobfinder
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"\\(green\\|yellow\\)\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12

  backend:
    image: luukien/jobfinder-backend:v1.0.2
    ports:
      - '8088:8088'
      - '8087:8087'
    container_name: jobfinder-backend
    networks:
      - jobfinder
    environment:
      SPRING_PROFILES_ACTIVE: prod
      OAUTH_GOOGLE_REDIRECT_URI: https://www.dinhkien.io.vn/login/oauth2/code/google

    #    command: ["--spring.profiles.active=prod"]
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

networks:
  jobfinder:
    driver: bridge
volumes:
  esdata:
    driver: local
  postgres-data:
    driver: local
